"""Help

Revision ID: cdfccc0c58f7
Revises: 80a05b76aa9b
Create Date: 2023-11-29 10:56:08.788644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdfccc0c58f7'
down_revision = '80a05b76aa9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.drop_column('who_favorited')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_submissions')
        batch_op.drop_column('user_favorites')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_favorites', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('user_submissions', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('who_favorited', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
